services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  designerei\ConplateFrameworkBundle\:
    resource: ../src
    exclude: ../src/{ContaoManager,DependencyInjection}

  designerei\ConplateFrameworkBundle\Controller\ContentElement\ImagesController:
    arguments:
      - '@security.helper'
      - '@contao.filesystem.virtual.files'
      - '@contao.image.studio'
      - '%contao.image.valid_extensions%'